# Generated by cucumber-sinatra. (2014-10-06 11:42:14 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/database.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = database

class databaseWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  databaseWorld.new
end
